module.exports = [
	"Alexander Kjellberg",
	"Anton Håkansson",
	"Anton Roegner Kinnmark",
	"Axel Carlberg",
	"Christoffer Ridderland",
	"Dadi Andrason",
	"Daniel Persson",
	"Edvin Lundqvist Sternvik",
	"Edvin Nilsson",
	"Elias Falk",
	"Emil Willbas ",
	"Emrik Östling",
	"Erik Hellman",
	"Erik Päts",
	"Fabian Beskow",
	"Felix Johansson",
	"Filip Rakic",
	"Gabriel Pfeiffer",
	"Isak Roos",
	"Jenny Turner",
	"Joel Martinsson",
	"Johan Scherman",
	"Johan Wheeler",
	"Jonathan Sundh",
	"Julius Eliasson",
	"Kevin Jeryd",
	"Lisa Strand",
	"Lukas Abel",
	"Lukas Artursson",
	"Mohammad El-Ali",
	"Nasir Alzanbouri",
	"Oliver Andreasson",
	"Oscar Litorell",
	"Patrik Lussi",
	"Petter Halling",
	"Petter Isaksson",
	"Rickard Larsen",
	"Samuel Marander",
	"Simon Lindwall",
	"Sofia Tuneld",
	"Thorbjörn Engdahl",
	"Viktor Blücker Bäckström",
	"Vincent Hellner",
];
